### ISSUE TITLE
readme

### ISSUE THREAD

**Issue by canda** [elementumscm/workshop-roboticsjs#2]
Esto está en inglés `Where <username> is your login user name in linux, /dev/ttyACM0 is the detected device of your Arduino board, the name may actually change depending on the board.`
EjecutandO => `Ejecutandp $ lsusb con...` 

Si se puede agregar los links a los drivers que ya conocemos joya

**Comment by canda** [comment]
flashearlo => `...deberemos flashealo.`

**Comment by canda** [comment]
Flasheando => `Flasheand un NodeMCU`

**Comment by canda** [comment]
el kit 5 dice 4 
https://github.com/elementumscm/workshop-roboticsjs/tree/chore/documentation/kit5

**Comment by chefguevara** [comment]
Fixed
